import 'dart:convert';
import 'dart:io';

import 'package:alephbits_content/reading_pack/compile_runner.dart';
import 'package:alephbits_content/reading_pack/json_writer.dart';
import 'package:alephbits_content/reading_pack/parser.dart';
import 'package:path/path.dart' as p;
import 'package:test/test.dart';

void main() {
  final repoRoot = p.normalize(p.join(Directory.current.path));
  final demoPack = p.join(repoRoot, 'books/hgp8iy3x/pl');

  String? resolveLongPack() {
    // Prefer book that still contains the Kowalska sample prose.
    for (final bookDir in Directory(p.join(repoRoot, 'books')).listSync()) {
      if (bookDir is! Directory) continue;
      final md = File(p.join(bookDir.path, 'pl', 'reading-pack.md'));
      if (!md.existsSync()) continue;
      final text = md.readAsStringSync();
      if (text.contains('Dr Anna Kowalska')) {
        return p.join(bookDir.path, 'pl');
      }
    }
    return null;
  }

  group('compile_pack', () {
    test('parses demo reading-pack.md', () {
      final markdown =
          File(p.join(demoPack, 'reading-pack.md')).readAsStringSync();
      final doc = ReadingPackParser().parse(markdown, packDirPath: demoPack);
      expect(doc.title, 'Spacer po Krakowie');
      expect(doc.quiz?.questions.length, 5);
    });

    test('parses Text section with in-body chapter headings', () {
      final pack = resolveLongPack();
      expect(pack, isNotNull, reason: 'expected a long editorial pack');
      final markdown = File(p.join(pack!, 'reading-pack.md')).readAsStringSync();
      final doc = ReadingPackParser().parse(markdown, packDirPath: pack);
      expect(doc.text, contains('Dr Anna Kowalska'));
      expect(doc.text.split(RegExp(r'\s+')).length, greaterThan(1500));
    });

    test('compiles trust, edition, and generated markers', () {
      final compiled = compilePackDirectory(demoPack);
      final lesson = jsonDecode(compiled.lessonJson) as Map<String, dynamic>;
      expect(lesson['editionVersion'], '1.0.1');
      expect(lesson['trustClassification'], 'demo');
      expect(lesson['subtitle'], isNotEmpty);
      expect(lesson['generatedBy'], 'compile_pack');
      expect(lesson['generatedFrom'], 'reading-pack.md');
      expect(compiled.licenseMd, contains('GENERATED by compile_pack'));
      final quiz = jsonDecode(compiled.quizJson) as Map<String, dynamic>;
      expect(quiz['generatedBy'], 'compile_pack');
    });

    test('compiles demo pack without drift', () {
      final result = compileAndCheckDirectory(demoPack);
      expect(result.parseError, isNull, reason: result.parseError);
      expect(
        result.drift,
        isEmpty,
        reason: result.drift.map((d) => d.file).join(', '),
      );
    });

    test('compiler output is deterministic', () {
      final first = compilePackDirectory(demoPack);
      final second = compilePackDirectory(demoPack);
      expect(first.lessonJson, second.lessonJson);
      expect(first.textTxt, second.textTxt);
      expect(first.quizJson, second.quizJson);
      expect(first.provenanceJson, second.provenanceJson);
      expect(first.licenseMd, second.licenseMd);
    });

    test('generated lesson.json matches committed file semantically', () {
      final compiled = compilePackDirectory(demoPack);
      final committed = File(p.join(demoPack, 'lesson.json')).readAsStringSync();
      expect(jsonSemanticallyEqual(committed, compiled.lessonJson), isTrue);
    });

    test('compiler consumes reading-pack.md only (not quiz.json)', () {
      final md = File(p.join(demoPack, 'reading-pack.md')).readAsStringSync();
      expect(md, contains('## Quiz'));
      final compiled = compilePackDirectory(demoPack);
      // Mutating quiz.json on disk must not change compile output.
      final quizPath = File(p.join(demoPack, 'quiz.json'));
      final original = quizPath.readAsStringSync();
      quizPath.writeAsStringSync('{"title":"tampered","questions":[]}');
      addTearDown(() => quizPath.writeAsStringSync(original));
      final again = compilePackDirectory(demoPack);
      expect(again.quizJson, compiled.quizJson);
    });
  });
}
