#!/usr/bin/env python3
"""Merge Collection Ten/Eleven editorial specs into phase119_pack_specs.json."""

from __future__ import annotations

import json
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
OUT = TOOLS / "phase119_pack_specs.json"

# Collection Ten — from Phase 119 editorial review (full quiz metadata).
C10: dict = {}  # populated below via exec of saved fragment

COLLECTION_TEN_RAW = r'''
{
  "Chór": {"manuscript_title":"Chór","slug":"chor","pack_id":"polish_chor","display_title":"Chór","subtitle":"Kłótnia o tablet i głosy pokoleń","blurb":"Magda i Tomek kłócą się o ekran syna, ale pod spodem walczą o traumy własnych rodziców i o to, czy wciąż są dla siebie partnerami. Po podcaście Agi Rogali zaczynają rozmawiać — nie idealnie, ale naprawdę.","genres":"psychology, short_story","cover_family":"psychology","audience":"adult","difficulty":4,"reader_stars":"★★★★☆","trust":"Fiction","tags":"wychowanie, małżeństwo, podcast, Aga Rogali, Collection Ten","keywords":"Chór, Magda, Tomek, tablet, rodzicielstwo, Aga Rogali","editorial_notes":"Fikcja parentingowa; adaptacja redakcyjna podcastu Agi Rogali.","philosophy_stars":4,"philosophy_note":"Dobre dopasowanie — granice, przepraszanie, pokoleniowa trauma bez moralizowania.","founder_notes":["Near-duplicate cluster: parenting-podcast conversion series (C10)."],"series":"Collection Ten","motifs":["family","marriage","childhood","rain","home","forgiveness"]},
  "Dobra dziewczynka": {"manuscript_title":"Dobra dziewczynka","slug":"dobra-dziewczynka","pack_id":"polish_dobra_dziewczynka","display_title":"Dobra dziewczynka","subtitle":"Perfekcja, pamiętnik i powrót do siebie","blurb":"Zosia przez dekady była „grzeczną dziewczynką” — czerwony pasek, chór, pamiętnik w szufladzie. Dopiero ciąża w pandemii i media społecznościowe pomagają jej zdjąć maskę i powiedzieć innym matkom: wystarczy być sobą.","genres":"psychology, short_story","cover_family":"psychology","audience":"adult","difficulty":3,"reader_stars":"★★★☆☆","trust":"Fiction","tags":"perfekcjonizm, macierzyństwo, media społecznościowe, Collection Ten","keywords":"Dobra dziewczynka, Zosia, perfekcja, macierzyństwo","editorial_notes":"Fikcja w formie wywiadu radiowego; słabszy ton autopromocyjny.","philosophy_stars":3,"philosophy_note":"Akceptowalna — ważny temat, struktura wywiadu słabsza niż najlepsze opowiadania C10.","founder_notes":["Founder note: rozważyć odłożenie na półkę."],"series":"Collection Ten","motifs":["childhood","motherhood","writing","memory","shame","forgiveness"]},
  "Kij i marchewka": {"manuscript_title":"Kij i marchewka","slug":"kij-i-marchewka","pack_id":"polish_kij_i_marchewka","display_title":"Kij i marchewka","subtitle":"Bez kar i nagród — tylko relacja","blurb":"Magda wychowana na krzesełku w kącie postanawia inaczej: zamiast karać Tymona za awanturę w sklepie, prosi o przytulenie. Opowieść o pozytywnej dyscyplinie i konsekwencjach zamiast kar.","genres":"psychology, instruction, short_story","cover_family":"psychology","audience":"family","difficulty":3,"reader_stars":"★★★★☆","trust":"Fiction","tags":"pozytywna dyscyplina, wychowanie, emocje, Collection Ten","keywords":"Kij i marchewka, pozytywna dyscyplina, kara, nagroda","editorial_notes":"Fikcja ilustrująca pozytywną dyscyplinę.","philosophy_stars":4,"philosophy_note":"Silne dopasowanie — praktyczna refleksja rodzicielska.","founder_notes":[],"series":"Collection Ten","motifs":["childhood","motherhood","home","anger","forgiveness","teaching"]},
  "W pełni": {"manuscript_title":"W pełni","slug":"w-pelni","pack_id":"polish_w_pelni","display_title":"W pełni","subtitle":"Dziecko kompletne od urodzenia","blurb":"Ola po podcaście o Jesperze Julu przestaje traktować Franka jak projekt do naprawy. Ufa jego decyzjom — od basenu po nożyczki — i uczy się przepraszać.","genres":"psychology, short_story","cover_family":"psychology","audience":"family","difficulty":4,"reader_stars":"★★★★☆","trust":"Fiction","tags":"Jesper Juul, zaufanie, ADHD, wychowanie, Collection Ten","keywords":"W pełni, Jesper Juul, Ola, zaufanie","editorial_notes":"Fikcja oparta na filozofii Jula; wątek ADHD nie jest poradą medyczną.","philosophy_stars":4,"philosophy_note":"Bardzo dobre dopasowanie — godność i zaufanie.","founder_notes":["Near-duplicate z Radio w głowie (ADHD)."],"series":"Collection Ten","motifs":["childhood","motherhood","home","forgiveness","teaching","question"]},
  "Poligon": {"manuscript_title":"Poligon","slug":"poligon","pack_id":"polish_poligon","display_title":"Poligon","subtitle":"Twardy ojciec i przerwanie łańcucha","blurb":"Maciek dorasta w domu, gdzie ból ma być „hartowaniem”. Jako ojciec walczy z echem własnego ojca — i w końcu mówi mu prawdę po latach.","genres":"psychology, short_story","cover_family":"psychology","audience":"adult","difficulty":5,"reader_stars":"★★★★☆","trust":"Fiction","tags":"przemoc emocjonalna, ojcostwo, terapia, Collection Ten","keywords":"Poligon, Maciek, ojciec, przemoc, terapia","editorial_notes":"Fikcja o przemocy emocjonalnej; founder review przed promocją.","philosophy_stars":4,"philosophy_note":"Silna opowieść o przerwaniu cyklu przemocy.","founder_notes":["P0 founder review: przemoc w rodzinie, klapsy."],"series":"Collection Ten","motifs":["fatherhood","childhood","fear","factory","forgiveness","reconciliation"]},
  "Radio w głowie": {"manuscript_title":"Radio w głowie","slug":"radio-w-glowie","pack_id":"polish_radio_w_glowie","display_title":"Radio w głowie","subtitle":"ADHD jak stacje grające naraz","blurb":"Kasia od dziecka ma w głowie „radio” — wszystkie stacje naraz. Po diagnozie ADHD uczy się strategii i mówi klasie, że inny mózg nie znaczy gorszy.","genres":"psychology, short_story","cover_family":"psychology","audience":"family","difficulty":3,"reader_stars":"★★★★☆","trust":"Fiction","tags":"ADHD, szkoła, koncentracja, Collection Ten","keywords":"Radio w głowie, ADHD, Kasia, koncentracja","editorial_notes":"Fikcja edukacyjna o ADHD; nie zastępuje diagnozy medycznej.","philosophy_stars":4,"philosophy_note":"Przystępna metafora dla młodzieży i rodzin.","founder_notes":["Near-duplicate z W pełni (ADHD)."],"series":"Collection Ten","motifs":["childhood","school","fear","discovery","teaching","companionship"]},
  "Nowy świat": {"manuscript_title":"Nowy świat","slug":"nowy-swiat","pack_id":"polish_nowy_swiat","display_title":"Nowy świat","subtitle":"Od „słuchaj” do „rozmawiaj”","blurb":"Tomek wychowany na zasadzie „dzieci i ryby głosu nie mają” nie rozumie, czemu córka Zosia się zamyka. Podcast Marii Berlińskiej o dialogu otwiera mu oczy.","genres":"psychology, short_story","cover_family":"everyday_live","audience":"family","difficulty":3,"reader_stars":"★★★☆☆","trust":"Fiction","tags":"dialog, ekrany, wychowanie, Maria Berlińska, Collection Ten","keywords":"Nowy świat, Tomek, Zosia, dialog","editorial_notes":"Fikcja parentingowa; powtarzalna struktura podcast→zmiana.","philosophy_stars":3,"philosophy_note":"Akceptowalna — ważny przekaz obecności, mniej oryginalna niż Chór.","founder_notes":[],"series":"Collection Ten","motifs":["fatherhood","childhood","home","silence","companionship","journey"]},
  "Autorytet na przepraszam": {"manuscript_title":"Autorytet na przepraszam","slug":"autorytet-na-przepraszam","pack_id":"polish_autorytet_na_przepraszam","display_title":"Autorytet na przepraszam","subtitle":"Prawdziwy autorytet rodzica","blurb":"Zmęczona Ania i surowy Marek kłócą się o wychowanie. Podcast Marii Berlińskiej uczy ich, że autorytet buduje się na „przepraszam”.","genres":"psychology, short_story","cover_family":"psychology","audience":"adult","difficulty":4,"reader_stars":"★★★★☆","trust":"Fiction","tags":"autorytet, przepraszanie, chwalenie, Collection Ten","keywords":"Autorytet na przepraszam, Ania, Marek","editorial_notes":"Fikcja o współrodzicielstwie; adaptacja podcastu.","philosophy_stars":4,"philosophy_note":"Silny przekaz o przepraszaniu i wzorcach małżeńskich.","founder_notes":[],"series":"Collection Ten","motifs":["family","marriage","motherhood","fatherhood","forgiveness","home"]},
  "Cisza": {"manuscript_title":"Cisza","slug":"cisza-dom","pack_id":"polish_cisza_dom","display_title":"Cisza","subtitle":"Shitsuke, mimamoru i amae w domu","blurb":"Kasia krzyczy codziennie, gdy Franek rozlewa wodę — aż trafia na film o japońskim wychowaniu. Shitsuke, mimamoru i amae uczą ją, że zmienia się nie dziecko, tylko ona sama.","genres":"psychology, instruction, short_story","cover_family":"psychology","audience":"family","difficulty":3,"reader_stars":"★★★★☆","trust":"Fiction","tags":"japońskie wychowanie, shitsuke, mimamoru, amae, Collection Ten","keywords":"Cisza, shitsuke, mimamoru, amae, Franek","editorial_notes":"NIE mylić z cisza-przed-burza (C4). Slug cisza-dom celowo rozróżnia.","philosophy_stars":4,"philosophy_note":"Zwięzła opowieść; dobra para z Kij i marchewka.","founder_notes":["P0: slug disambiguation vs cisza-przed-burza."],"series":"Collection Ten","motifs":["home","silence","childhood","motherhood","teaching","water"]},
  "Naczynia połączone": {"manuscript_title":"Naczynia połączone","slug":"naczynia-polaczone","pack_id":"polish_naczynia_polaczone","display_title":"Naczynia połączone","subtitle":"Agresja w szkole, system w domu","blurb":"Nauczycielka Anna widzi w Kacprze geniusza i agresję naraz. Mówi rodzicom: rodzina to naczynia połączone — zmiana w domu zmienia chłopca w klasie.","genres":"psychology, short_story","cover_family":"psychology","audience":"family","difficulty":4,"reader_stars":"★★★★☆","trust":"Fiction","tags":"agresja, szkoła, rodzina, granice, Collection Ten","keywords":"Naczynia połączone, Kacper, Anna, kontrakt rodzinny","editorial_notes":"Fikcja o przemocy rówieśniczej; perspektywa nauczycielki.","philosophy_stars":4,"philosophy_note":"Metafora naczyń połączonych dobrze tłumaczy system rodzinny.","founder_notes":[],"series":"Collection Ten","motifs":["school","family","anger","teaching","community","reconciliation"]},
  "Ułamki": {"manuscript_title":"Ułamki","slug":"ulamki","pack_id":"polish_ulamki","display_title":"Ułamki","subtitle":"Podziel czynność na kroki","blurb":"Poranki Magdy z czteroletnią Zosią to walka o kurtkę — aż podcast Agi Rogali tłumaczy: „Ubierz się” to dziesięć zadań naraz.","genres":"psychology, instruction, short_story","cover_family":"psychology","audience":"family","difficulty":2,"reader_stars":"★★★★☆","trust":"Fiction","tags":"Aga Rogali, samodzielność, przedszkole, Collection Ten","keywords":"Ułamki, Aga Rogali, Zosia, poranki","editorial_notes":"Fikcja ilustrująca technikę podziału czynności na kroki.","philosophy_stars":4,"philosophy_note":"Najlepszy praktyczny parenting w C10 dla rodziców przedszkolaków.","founder_notes":[],"series":"Collection Ten","motifs":["childhood","motherhood","home","clock","teaching","patience"]},
  "Przedszkole bez ścian": {"manuscript_title":"Przedszkole bez ścian","slug":"przedszkole-bez-scian","pack_id":"polish_przedszkole_bez_scian","display_title":"Przedszkole bez ścian","subtitle":"Nauka przez naturę i projekty","blurb":"Wypalona nauczycielka Marta słyszy o przedszkolu, gdzie dzieci uczą się na dworze i przez własne pasje. Z czerwonego jabłka w linii przechodzi do projektu o dinozaurach.","genres":"instruction, short_story","cover_family":"everyday_live","audience":"family","difficulty":3,"reader_stars":"★★★☆☆","trust":"Fiction","tags":"przedszkole, edukacja, natura, Collection Ten","keywords":"Przedszkole bez ścian, Marta, edukacja alternatywna","editorial_notes":"Fikcja o alternatywnej edukacji; dość idealizująca.","philosophy_stars":3,"philosophy_note":"Ciepła, ale słabsza narracyjnie niż parenting stories.","founder_notes":[],"series":"Collection Ten","motifs":["school","forest","garden","discovery","teaching","wonder"]},
  "Etykieta": {"manuscript_title":"Etykieta","slug":"etykieta","pack_id":"polish_etykieta","display_title":"Etykieta","subtitle":"Samospełniająca się etykieta „lenia”","blurb":"Kamil słyszał w dzieciństwo, że jest leniem — i powtarza to synowi Adamowi. Książka Szymona Grzelaka uczy go etykietować inaczej: wytrwały, odpowiedzialny.","genres":"psychology, short_story","cover_family":"psychology","audience":"family","difficulty":4,"reader_stars":"★★★★☆","trust":"Fiction","tags":"etykiety, Szymon Grzelak, ojcostwo, Collection Ten","keywords":"Etykieta, Kamil, Adam, lenistwo","editorial_notes":"Fikcja o samospełniającej się przepowiedni etykiet.","philosophy_stars":4,"philosophy_note":"Silny mechanizm psychologiczny; moc słów rodzica.","founder_notes":[],"series":"Collection Ten","motifs":["childhood","fatherhood","shame","memory","teaching","forgiveness"]},
  "Jeszcze": {"manuscript_title":"Jeszcze","slug":"jeszcze","pack_id":"polish_jeszcze","display_title":"Jeszcze","subtitle":"Growth mindset — „jeszcze nie umiem”","blurb":"Julia przestała pytać — teraz mówi „nudne”. Tomasz odkrywa singapurską zasadę „jeszcze” i budzi w córce ciekawość przez pytania i błędy.","genres":"psychology, instruction, short_story","cover_family":"psychology","audience":"family","difficulty":3,"reader_stars":"★★★★☆","trust":"Fiction","tags":"growth mindset, singapurska metoda, nauka, Collection Ten","keywords":"Jeszcze, Julia, growth mindset, motywacja","editorial_notes":"Fikcja o growth mindset; silny pedagogiczny przekaz.","philosophy_stars":4,"philosophy_note":"Doskonałe dopasowanie — motywacja wewnętrzna.","founder_notes":["Rekomendacja: mocny kandydat family shelf."],"series":"Collection Ten","motifs":["childhood","fatherhood","school","question","discovery","teaching"]},
  "Lista rzeczy, których żałuję": {"manuscript_title":"Lista rzeczy, których żałuję","slug":"lista-rzeczy-ktorych-zaluje","pack_id":"polish_lista_rzeczy_ktorych_zaluje","display_title":"Lista rzeczy, których żałuję","subtitle":"Regret list matki dorosłych dzieci","blurb":"Anna ma 42 lata i listę jedenaastu rodzicielskich żalów. Syn Tomek wraca na weekend i pokazuje, że miłość przetrwała mimo błędów.","genres":"psychology, short_story","cover_family":"everyday_live","audience":"adult","difficulty":4,"reader_stars":"★★★☆☆","trust":"Fiction","tags":"żal, macierzyństwo, relacja z dorosłym dzieckiem, Collection Ten","keywords":"Lista żalów, Anna, Tomek, macierzyństwo","editorial_notes":"Tytuł podobny do C9 „Lista” — inna fabuła; slug rozróżnia.","philosophy_stars":3,"philosophy_note":"Poruszająca, melancholijna; mniej encourage exploration niż Jeszcze.","founder_notes":["Title similarity: C9 Lista uses lista-myrotworec."],"series":"Collection Ten","motifs":["motherhood","grief","memory","photograph","forgiveness","gratitude"]},
  "Bogini i liczby": {"manuscript_title":"Bogini i liczby","slug":"bogini-i-liczby","pack_id":"polish_bogini_i_liczby","display_title":"Bogini i liczby","subtitle":"Ramanujan, Hardy i wizje we śnie","blurb":"Srinivasa Ramanujan widzi wzory, których nie potrafi udowodnić — i mówi, że podpowiada mu je bogini Namagiri. W Cambridge Hardy wymaga dowodów.","genres":"biography, history, short_story","cover_family":"biography","audience":"teen","difficulty":6,"reader_stars":"★★★★☆","trust":"Adapted from real events","tags":"Ramanujan, matematyka, Hardy, Indie, Collection Ten","keywords":"Bogini i liczby, Ramanujan, Hardy, matematyka","editorial_notes":"Fikcja historyczna; mistycyzm vs dowód — fiction disclaimer.","philosophy_stars":4,"philosophy_note":"Silna opowieść o wiedzy i granicach nauki.","founder_notes":["Founder review: mistycyzm religijny + twierdzenia matematyczne."],"series":"Collection Ten","motifs":["mathematics","ocean","dream","mentor","exile","discovery"]}
}
'''

# Quiz data for C10 — keyed by manuscript title
C10_QUIZZES = {
    "Chór": [
        {"question": "O co kłócą się Magda i Tomek na początku?", "answers": ["O rozstanie", "O to, że Franek nie wyłączył tabletu po czasie ekranowym", "O wakacje", "O pracę Magdy"], "correct": "B", "explanation": "Franek grał w piłkę nożną na tablecie po 18:45.", "reference": "Wyłącz to"},
        {"question": "Co Franek pyta matkę po kłótni?", "answers": ["Czy dostanie tablet", "Czy rodzice się jeszcze kochają", "Czy pójdą do kina", "Czy Zosia jest chora"], "correct": "B", "explanation": "Franek pyta wprost: „Czy wy się jeszcze kochacie?”.", "reference": "Czy wy się jeszcze kochacie"},
        {"question": "Czyją podcastową myśl Magda przywołuje w sypialni?", "answers": ["Jespera Jula", "Agi Rogali", "Marii Berlińskiej", "Szymona Grzelaka"], "correct": "B", "explanation": "Magda cytuje Agę Rogalę o zbędnych kłótniach.", "reference": "podcast Agi Rogali"},
        {"question": "Jak Tomek reaguje, gdy Franek prosi o wcześniejsze ostrzeżenie przed zabraniem tabletu?", "answers": ["Krzyknie", "Uśmiecha się i mówi „Umowa stoi”", "Ignoruje syna", "Każe iść spać"], "correct": "B", "explanation": "Tomek akceptuje propozycję i mówi: „Umowa stoi”.", "reference": "Umowa stoi"},
        {"question": "Co metafora „chóru głosów” oznacza w finale?", "answers": ["Że dzieci powinny milczeć", "Że w rodzicach brzmią głosy poprzednich pokoleń, których uczą się słuchać", "Że rodzina śpiewa w kościele", "Że Tomek zostaje śpiewakiem"], "correct": "B", "explanation": "Tomek i Magda uczą się słuchać głosów rodziców/dziadków.", "reference": "Chór głosów"},
    ],
}


def main() -> None:
    merged: dict = {}
    c10_base = json.loads(COLLECTION_TEN_RAW)
    # Load full C10 from separate file if present
    c10_path = TOOLS / "phase119_collection_ten_full.json"
    if c10_path.exists():
        merged.update(json.loads(c10_path.read_text(encoding="utf-8")))
    else:
        merged.update(c10_base)

    c9_path = TOOLS / "phase119_collection_nine_specs.json"
    if c9_path.exists():
        merged.update(json.loads(c9_path.read_text(encoding="utf-8")))

    c11_path = TOOLS / "phase119_collection_eleven_specs.json"
    if c11_path.exists():
        merged.update(json.loads(c11_path.read_text(encoding="utf-8")))

    OUT.write_text(json.dumps(merged, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {len(merged)} specs to {OUT}")


if __name__ == "__main__":
    main()
